## NumPy

* Stands for numerical python.
* Fundamental package for scientific computing in Python.
* It's extensive and capable of performing mathematical computations effectively and efficiently.

## Why use NumPy?

* You may be wondering because after all, Python has lists which are extremely useful.
* Lists are awesome, but NumPy has some advantages over lists. One of them is speed.
* When performing operations on large arrays, NumPy often performs several orders of magnitude faster than ordinary lists.
* NumPy has memory efficient arrays and optimized algorithms.
* NumPy also has multidimensional array data structures that can represent vectors and matrices. (A lot of machine learning algorithms rely on matrix operations.)
* NumPy also has a large number of optimized built-in mathematical functions. These allow for execution of a variety of complex mathematical computations very fast with very little code (read no complicated loops), making the programs easier to understand.

## Creating NumPy ndarrays

* nd stands for n-dimensional.
* ndarrays contain elements of the same type.

In [1]:
import numpy as np

* ndarrays can be created in two ways;
  * using python lists
  * using built-in NumPy functions

In [4]:
# using python lists

x = np.array([1, 2, 3, 4, 5])
print("x = {}".format(x))

x = [1 2 3 4 5]


## Terminologies

* **Rank** - In general, N-Dimensional arrays have rank N, e.g. a 2D array is a rank 2 array.
* **shape** - corresponds to the no. of rows and columns in an array. The shape of an ndarray can be obtained by using the `.shape` attribute. It returns a tuple of N positive integers that specify the sizes of each dimension.

In [5]:
print("x has dimensions: {}".format(x.shape))
print("x is an object of type: {}".format(type(x)))
print("The elements in x are of type: {}".format(x.dtype))

x has dimensions: (5,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: int64


In [7]:
x = np.array(["Hello", "World"])
print("x has dimensions: {}".format(x.shape))
print("x is an object of type: {}".format(type(x)))
print("The elements in x are of type: {}".format(x.dtype))

x has dimensions: (2,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U5


## Major difference btwn ndarrays and lists

* Python lists can contain elements of multiple datatypes while ndarray elements must be of the same datatype.

In [8]:
x = np.array([1, 2, "Hello", "World"])

print("x has dimensions: {}".format(x.shape))
print("x is an object of type: {}".format(type(x)))
print("The elements in x are of type: {}".format(x.dtype))

x has dimensions: (4,)
x is an object of type: <class 'numpy.ndarray'>
The elements in x are of type: <U21


We can see mixed datatypes during the creation of x above, but when printing out the dtype, we see that all elements in x are of type _Unicode String_.

## Multidimensional NumPy arrays

In [36]:
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])

print("Ed Sheeran - I'm in love with the shape of you. (-_-)")
print("Just kidding! The shape of y is ...")
print()
print(y)
print()

print("y has dimensions: {}".format(y.shape))

print("y has a total of {} elements.".format(y.size))
print("y is an object of type: {}".format(type(y)))
print("the elements in y are of type: {}".format(y.dtype))

Ed Sheeran - I'm in love with the shape of you. (-_-)
Just kidding! The shape of y is ...

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

y has dimensions: (4, 3)
y has a total of 12 elements.
y is an object of type: <class 'numpy.ndarray'>
the elements in y are of type: int64


## What is the dtype when we create ndarrays with other data types?

In [15]:
x = np.array([1, 2, 3])
y = np.array([1.0, 2.0, 3.0])
z = np.array([1, 2.5, 4])

print("The elements in x are of type: {}".format(x.dtype))
print("The elements in y are of type: {}".format(y.dtype))
print("The elements in z are of type: {}".format(z.dtype))

The elements in x are of type: int64
The elements in y are of type: float64
The elements in z are of type: float64


The `z` array is created with elements of different types but its dtype is `float64`. NumPy converts the ndarray elements to float in order to avoid losing precision in numerical computations. This is called _upcasting_.

Even though NumPy selects the dtype of the ndarray, it has the provision to allow you to specify the particular dtype you want to assign the elements inside the ndarray.
You specify the dtype when creating the ndarray using the keyword `dtype` in the `nd.array()` function.

In [17]:
x = np.array([1.5, 2.2, 3.7, 4.0, 5.9], dtype=np.int64)

print("This is x")
print()
print(x)
print()
print("The elements of x are of type {}".format(x.dtype))

This is x

[1 2 3 4 5]

The elements of x are of type int64


NumPy converted the ndarray to `int64` by removing the decimal part.
Specifying the `dtype` can be important when you don't want NumPy to accidentally choose the wrong datatype.

Once you create an ndarray, you may want to save it in a file to be read later or used by another program.

In [19]:
x = np.ndarray([1, 2, 3, 4, 5])

# save x in the current directory
np.save('x_np_array', x)

In [20]:
y = np.load('x_np_array.npy')

print("This is y")
print()
print(y)
print()
print("The elements of y are of type {}".format(y.dtype))

This is y

[[[[[0.00000000e+000 5.43472210e-323 6.92689230e-310 2.25465835e-314
     0.00000000e+000]
    [0.00000000e+000             nan 0.00000000e+000 1.00582130e-221
     0.00000000e+000]
    [4.44659081e-323 2.27648524e-314 6.92688973e-310 0.00000000e+000
     0.00000000e+000]
    [            nan 0.00000000e+000 2.12199579e-314 3.55727265e-322
     5.43472210e-323]]

   [[2.27648524e-314 6.92688973e-310 4.94065646e-324 1.18575755e-322
                 nan]
    [0.00000000e+000 2.12199579e-314 7.11454530e-322 5.43472210e-323
     2.27648524e-314]
    [6.92688973e-310 0.00000000e+000 1.38338381e-322             nan
     0.00000000e+000]
    [4.94065646e-324 1.06718180e-321 5.43472210e-323 2.27648524e-314
     6.92688973e-310]]

   [[0.00000000e+000 1.38338381e-322             nan 4.94065646e-323
     4.94065646e-324]
    [1.42290906e-321 3.95252517e-323 2.27648524e-314 6.92688973e-310
     0.00000000e+000]
    [5.92878775e-323             nan 0.00000000e+000 4.94065646e-324
     1

In [21]:
# not sure what's happening when we print y. Need to check it out later.

## creating NumPy ndarrays using built-in functions

NumPy provides the abilioty to create ndarrays using built-in functions.
These functions allow us to create certain kinds of functions using just one line of code.

### np.zeros(shape)
This function creates an ndarray that is full of zeroes of the given shape.

In [26]:
# e.g. a rank 2 array with 3 rows and 4 columns
x = np.zeros((3, 4))

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("Elements of x are type: {}".format(x.dtype))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

This is the shape of x: (3, 4)
Elements of x are type: float64


> By default, np.zeroes creates an ndarray with dtype of float64. The desired datatype can be acheived through the use of the dtype keyword.

### np.ones(shape)

Similarly, we can create an ndarray full of ones.

In [25]:
x = np.ones((3, 2))

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))


[[1. 1.]
 [1. 1.]
 [1. 1.]]

This is the shape of x: (3, 2)


Again, `np.ones()` creates an ndarray of dtype `float64`. This behaviour can be modified through the use of the `dtype` kwarg when creating the array.

### np.full(shape, constant_value)

The `np.full` function takes two arguments; the shape and the constant value with which to populate the ndarray.

In [27]:
x = np.full((4, 3), 34)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))


[[34 34 34]
 [34 34 34]
 [34 34 34]
 [34 34 34]]

This is the shape of x: (4, 3)


`np.full` creates an ndarray of the same dtype as the constant value.

### np.eye(rows)

This is used to create an identity matrix.

An identity matrix is a square matrix (rows == columns) that only has ones in its main diagonal and zeroes everywhere else.

In [29]:
x = np.eye(6)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

This is the shape of x: (6, 6)
This is the dtype of x: float64


> The default dtype of `np.eye` is `float64`. This can be changed via the `dtype` kwarg at the point of array creation.

### np.diag(diag)

This creates a **square** matrix that only has values along its main diagonal.

In [30]:
x = np.diag([10, 20, 30, 40])

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 40]]

This is the shape of x: (4, 4)
This is the dtype of x: int64


### np.arange(start, stop, step)

This creates an ndarray that has evenly spaced values within a specified interval.

Can be used with either one, two or three arguments.

In [31]:
# when used with only one argument, it creates an ndarray of rank 1 with consecutive integers between 0 and `stop` -1
x = np.arange(10)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[0 1 2 3 4 5 6 7 8 9]

This is the shape of x: (10,)
This is the dtype of x: int64


In [32]:
# when used with two arguments, it creates an ndarray with evenly spaced values between `start` and `stop` - 1
x = np.arange(4, 10)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[4 5 6 7 8 9]

This is the shape of x: (6,)
This is the dtype of x: int64


In [33]:
# when used with three arguments, it creates an ndarray with values between `start` and `stop` - 1 that evenly spaced by step intervals
x = np.arange(1, 14, 3)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[ 1  4  7 10 13]

This is the shape of x: (5,)
This is the dtype of x: int64


> `np.arange` allows for non-integer steps but the results may be incosistent with what you may expect due to finite floating point precision. For cases where non-integer steps are required, it's usually better to use `np.linspace()`

### np.linspace(start, stop, step)

Creates an ndarray with evenly spaced elements where `start` and `stop` are inclusive (unlike np.arange()). This means it needs to be called with at least two arguments.
When no step is provided, a default of 50 will be used.

In [37]:
x = np.linspace(0, 25, 10)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

This is the shape of x: (10,)
This is the dtype of x: float64


`np.linspace` works better than `np.arange` because it uses the step as the number of elements we want within interval 
rather than using the step as the value between elements.

By default, the stop value is included in `np.linspace`. To exclude it, use the `endpoint` boolean flag when creating the ndarray.

In [38]:
x = np.linspace(0, 25, 10, endpoint=False)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

This is the shape of x: (10,)
This is the dtype of x: float64


### np.reshape(nd_array, shape)

`np.arange` and `np.linspace` can also be used to create rank 2 ndarrays. This can be done by passing them to `np.reshape(nd_array, shape)`.

This converts `nd_array` to the specified `shape`.

It's important to note that `shape` should be compatible with the number of elements in the given `nd_array`, e.g. 

* you can convert a 6 element 1 rank array to a 3 X 2 rank 2 array or a 2 X 3 rank 2 array since both dimensions have a total of 6 elements.
* you cannot reshape a 6 element rank 1 to a 3 X 3 rank 2 because the rank 2 array needs 9 elements in total.

In [39]:
x = np.arange(20)

print("Original x")
print()
print(x)
print()
x = np.reshape(x, (4,5))
print("Reshaped x")
print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))

Original x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped x

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

This is the shape of x: (4, 5)
This is the dtype of x: int64


One great feature about NumPy is that these built-in functions can also be chained in a single line!

In [41]:
x = np.arange(20).reshape(4, 5)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

This is the shape of x: (4, 5)
This is the dtype of x: int64


> Notice that when we chain, the call to `np.reshape` changes slightly. It is applied as `np.reshape(shape)`

Chaining can also be done with `np.linspace`

In [44]:
x = np.linspace(0, 50, 10, endpoint=False).reshape(5, 2)

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[[ 0.  5.]
 [10. 15.]
 [20. 25.]
 [30. 35.]
 [40. 45.]]

This is the shape of x: (5, 2)
This is the dtype of x: float64


### np.random.random(shape)

NumPy also has random ndarrays. They (obviously) contain random numbers.

`np.random.random` creates an ndarray of the specified shape with random floats within the `0.0 - 1.0` range.

In [45]:
x = np.random.random((3, 3))

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[[0.32055626 0.68693361 0.12290858]
 [0.02191445 0.06862056 0.33535179]
 [0.73944632 0.1167699  0.32899875]]

This is the shape of x: (3, 3)
This is the dtype of x: float64


### np.random.randint(start, stop, size=shape)

NumPy can also create ndarrays with random integers within a particular interval.

In [46]:
x = np.random.randint(4, 15, size=(3, 2))

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))


[[12 14]
 [10  8]
 [ 4  5]]

This is the shape of x: (3, 2)
This is the dtype of x: int64


### np.random.normal(mean, standard_deviation, size=shape)

Sometimes you want to create an ndarray that contains random numbers that satisfy certain statistical properties, e.g. if you want random numbers in the ndarray to have an average of 0.

Let's create a 1000 X 1000 ndarray of random floating point numbers drawn from a normal distribution with a mean of zero and a standard deviation of 1.

In [3]:
x = np.random.normal(0, 0.1, size=(1000, 1000))

print()
print(x)
print()
print("This is the shape of x: {}".format(x.shape))
print("This is the dtype of x: {}".format(x.dtype))
print("The elements of x have a mean of: {}".format(x.mean()))
print("The maximum value amongst elements of x is: {}".format(x.max()))
print("The minimum value amongst elements of x is: {}".format(x.min()))
print("x has {} positive numbers".format((x > 0).sum()))
print("x has {} negative numbers".format((x < 0).sum()))


[[-0.13750051 -0.09541567  0.04886007 ... -0.07755683  0.09764123
   0.08341097]
 [ 0.06122054  0.05456466  0.13947808 ...  0.16613004  0.15363135
   0.10380523]
 [ 0.02710184  0.04610862 -0.05827324 ...  0.01261966  0.07875748
   0.08462682]
 ...
 [ 0.05679053  0.18078767  0.03625664 ... -0.00937658 -0.11226394
  -0.01892757]
 [-0.05172534  0.16272606  0.09297124 ... -0.08393974 -0.03597898
   0.05998518]
 [-0.24345125 -0.03027278 -0.07134866 ... -0.02936495 -0.07807936
  -0.02892631]]

This is the shape of x: (1000, 1000)
This is the dtype of x: float64
The elements of x have a mean of: 0.0002146426715178508
The maximum value amongst elements of x is: 0.48054886738071706
The minimum value amongst elements of x is: -0.5196125290505974
x has 500852 positive numbers
x has 499148 negative numbers


### Accessing, deleting and inserting elements into ndarrays

We now know how to create ndarrays. Now, we'll look into how NumPy allows us to effectively manipulate data within ndarrays.

ndarrays are mutable. They can also be sliced, which means that they can be split in many different ways. This allows us to retrieve any subset of the ndarray we want.

Elements can be accessed using indices inside square brackets. Both positive and negative indices can be used.

Positive indices accesss elements from the beginning of the array while negative indices are used to access elements from the end of the array.

In [5]:
x = np.array([1, 2, 3, 4, 5])

print()
print(x)
print()

# positive indices
print("This is the first element: {}".format(x[0]))
print("This is the second element: {}".format(x[1]))
print("This is the last element: {}".format(x[4]))
print()

# negative indices
print("This is the first element: {}".format(x[-5]))
print("This is the second element: {}".format(x[-4]))
print("This is the last element: {}".format(x[-1]))


[1 2 3 4 5]

This is the first element: 1
This is the second element: 2
This is the last element: 5

This is the first element: 1
This is the second element: 2
This is the last element: 5


#### Changing elements in an ndarray

* Rank 1 arrays

In [12]:
x = np.array([1, 2, 3, 4, 5])

print("Original x")
print()
print(x)
print()

x[3] = 20

print("Modified x")
print()
print(x)
print()

Original x

[1 2 3 4 5]

Modified x

[ 1  2  3 20  5]



* Rank 2 arrays

To modify elements for these arrays, we need to provide two indices in the form of `[row, column]`.

In [13]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print()
print(x)
print()

print("This is (0, 0) in x: {}".format(x[0, 0]))
print("This is (0, 1) in x: {}".format(x[0, 1]))
print("This is (2, 2) in x: {}".format(x[2, 2]))

print("Original x")
print()
print(x)
print()

x[1, 1] = 500

print("Modified x")
print()
print(x)
print()


[[1 2 3]
 [4 5 6]
 [7 8 9]]

This is (0, 0) in x: 1
This is (0, 1) in x: 2
This is (2, 2) in x: 9
Original x

[[1 2 3]
 [4 5 6]
 [7 8 9]]

Modified x

[[  1   2   3]
 [  4 500   6]
 [  7   8   9]]



#### Deleting items in an ndarray

* Elements can be deleted using the `np.delete(ndarray, elements, axis)` function.
* This function deletes the given list of `elements` from the given `ndarray` along the specified `axis`.
* For rank 1 arrays, axis is not required.
* For rank 2 arrays, `axis=0` selects rows while `axis=1` selects columns

In [22]:
# rank 1 arrays
x = np.array([1, 2, 3, 4, 5])

print("Original x")
print()
print(x)
print()

# delete the first and last element of x
x = np.delete(x, [0,4])

print("Modified x")
print()
print(x)
print()

# rank 2 arrays
y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Original y")
print()
print(y)
print()

# delete the first row of y
w = np.delete(y, 0, axis=0)

print("How y would look like without the first row")
print()
print(w)
print()

# delete the first and last column of y
v = np.delete(y, [0, 2], 1)

print("How y would look like without the first and last column")
print()
print(v)
print()

Original x

[1 2 3 4 5]

Modified x

[2 3 4]

Original y

[[1 2 3]
 [4 5 6]
 [7 8 9]]

How y would look like without the first row

[[4 5 6]
 [7 8 9]]

How y would look like without the first and last column

[[2]
 [5]
 [8]]



#### Appending values to ndarrays

*  We use the `np.append(ndarray, elements, axis)` function for this.
*  This function appends the given list of `elements` to `ndarray` along the specified `axis`.

In [35]:
# rank 1 arrays
x = np.array([1, 2, 3, 4, 5])

print("Original x")
print()
print(x)
print()

# append the integer 6 to x
x = np.append(x, 6)

print("Modified x")
print()
print(x)
print()

# append the integers 7 and 8 to x
x = np.append(x, [7, 8])

print("Further modified x")
print()
print(x)
print()

# rank 2 arrays
y = np.array([[1, 2, 3], [4, 5, 6]])

print("Original y")
print()
print(y)
print()

# append a row containing [7, 8, 9] to y
y = np.append(y, [[7, 8, 9]], axis=0)

print("y modified with extra row [7,8,9]")
print()
print(y)
print()

# append a new column containing 9 and 10
y = np.append(y, [[9], [10], [11]], axis=1)

print("y modified with extra column containing 9 and 10")
print()
print(y)
print()

Original x

[1 2 3 4 5]

Modified x

[1 2 3 4 5 6]

Further modified x

[1 2 3 4 5 6 7 8]

Original y

[[1 2 3]
 [4 5 6]]

y modified with extra row [7,8,9]

[[1 2 3]
 [4 5 6]
 [7 8 9]]

y modified with extra column containing 9 and 10

[[ 1  2  3  9]
 [ 4  5  6 10]
 [ 7  8  9 11]]



#### Inserting values in ndarrays

*  `np.insert(ndarray, index, elements, axis)` is the function of interest.
*  This inserts the given list of `elements` to `ndarray` right before the given `index` aling the specified `axis`.

In [40]:
# rank 1 array
x = np.array([1, 2, 5, 6 ,7])

print("Original x")
print()
print(x)
print()

# insert 3 and 4 between 2 and 5
x = np.insert(x, 2, [3, 4])

print("Modified x")
print()
print(x)
print()

# rank 2 arrays
y = np.array([[1, 2, 3], [7, 8, 9]])

print("Original y")
print()
print(y)
print()

# insert a row between the first and last row of y
y = np.insert(y, 1, [[4, 5, 6]], 0)

print("Modified y")
print()
print(y)
print()

Original x

[1 2 5 6 7]

Modified x

[1 2 3 4 5 6 7]

Original y

[[1 2 3]
 [7 8 9]]

Modified y

[[1 2 3]
 [4 5 6]
 [7 8 9]]



#### Stacking

NumPy allows stacking of ndarrays on top of each other or side by side.

Stacking is done using either `np.vstack` (for vertical stacking) or `np.hstack` (for horizontal stacking).

In order to stack ndarrays, their **SHAPES MUST MATCH**!

In [43]:
x = np.array([1, 2])

y = np.array([[3, 4], [5, 6]])

print("x")
print()
print(x)
print()

print("y")
print()
print(y)
print()

# stack x on top of y
z = np.vstack((x, y))

print("stacking x on top of y")
print()
print(z)
print()

# stack x on the right of y. Reshape needed.
w = np.hstack((y, x.reshape(2, 1)))

print("stacking x to the right of y")
print()
print(w)
print()


x

[1 2]

y

[[3 4]
 [5 6]]

stacking x on top of y

[[1 2]
 [3 4]
 [5 6]]

stacking x to the right of y

[[3 4 1]
 [5 6 2]]



### Slicing ndarrays

In addition to being able to access individual elements one at a time, NumPy provides a way to access subsets of ndarrays. This is called slicing.

In general, there are three types of slicing;

```
1. ndarray[start: end]
2. ndarray[start:]
3. ndarray[:end]
```

> The end index is excluded.

> Since ndarrays are multidimensional, when slicing you have to specify a slice for each dimension of the array.

We'll look at some examples on how to slice a rank 2 array.

In [9]:
x = np.arange(20).reshape(4, 5)

print("x is ...")
print()
print(x)
print()

# select all the elements that are in the 2nd through 4th rows
# and in the 3rd and 5th columns
z = x[1:4, 2:5]

print("z is ...")
print()
print(z)
print()

# select all the elements in the 1st through 3rd rows
# and 3rd through 4th columns
w = x[:3, 2:5]

print("w is ...")
print()
print(w)
print()

x is ...

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

z is ...

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

w is ...

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]]



#### np.copy(ndarray)

Changing any of the slices above will change `x` as well.

Using `np.copy(ndarray)` will create a copy of the given ndarray.

This function can also be chained as with `reshape`.

In [11]:
x = np.arange(20).reshape(4, 5)

print("x is ...")
print()
print(x)
print()

# create a copy of the slice
z = x[1:4, 2:5].copy()

print("z is ...")
print()
print(z)
print()

# change an element in z
z[2,2] = 555

print("x is ...")
print()
print(x)
print()

print("z is ...")
print()
print(z)
print()



x is ...

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

z is ...

[[ 7  8  9]
 [12 13 14]
 [17 18 19]]

x is ...

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

z is ...

[[  7   8   9]
 [ 12  13  14]
 [ 17  18 555]]



By using `copy`, we are creating new ndarrays that are independent of each other.

> Skipped some stuff about diagnoals, unique etc.

### Boolean indexing, set operations and sorting

Slicing is useful when we know the exact indices of the elements we want to select. However, there are instances where we don't know indices of the elements we want to select. 

e.g. if we have a 10000 X 10000 ndarray of random integers ranging from 1 to 15000 and we only want to select those whose value is less than 20.

#### Boolean indexing 

Boolean indexing can help in the case above. It allows us to select elements using logical arguments instead of explicit indices.

In [16]:
x = np.arange(20).reshape(4, 5)

print("x is ...")
print()
print(x)
print()

# we use boolean indexing to select elements in x
print("The elements in x that are greater than 10: {}".format(x[x > 10]))
print("The elements in x that are less than or equal to 7: {}".format(x[x <= 7]))
print("The elements in x that are between 10 and 17: {}".format(x[(x > 10) & (x < 17)]))

x is ...

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

The elements in x that are greater than 10: [11 12 13 14 15 16 17 18 19]
The elements in x that are less than or equal to 7: [0 1 2 3 4 5 6 7]
The elements in x that are between 10 and 17: [11 12 13 14 15 16]


We can also assign values based on boolean indexing.

In [17]:
# all the elements whose value is between 10-17 should change to -1
x[(x > 10) & (x < 17)] = -1

print("x is ...")
print()
print(x)
print()

x is ...

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 17 18 19]]



#### set operations

This is useful when comparing ndarrays e.g. to find elements that are common between two ndarrays.

In [25]:
x = np.array([1, 2, 3, 4, 5])

y = np.array([6, 7, 2, 8, 4])

print("x is ...")
print()
print(x)
print()

print("y is ...")
print()
print(y)
print()

# use set operations to compare x and y
print()
print("The elements that are in both x and y: {}".format(np.intersect1d(x, y)))
print("The elements that are in x but not in y: {}".format(np.setdiff1d(x, y)))
print("All the elements in x and y: {}".format(np.union1d(x, y)))

x is ...

[1 2 3 4 5]

y is ...

[6 7 2 8 4]


The elements that are in both x and y: [2 4]
The elements that are in x but not in y: [1 3 5]
All the elements in x and y: [1 2 3 4 5 6 7 8]


#### sorting

`np.sort` can either be used as a function or as a method. However, there is a difference between its use as a function or as a method.

When using `np.sort()`, it sorts the ndarrays out of place (it doesn't change the array being sorted).

When using `ndarray.sort()`, it will sort the array in place, meaning the original array will be changed to the sorted one.

In [28]:
# create an unsorted rank 1 ndarray
x = np.random.randint(1, 11, size=(10, ))

print("Original x is ...")
print()
print(x)
print()

# sorting as a function
print()
print("Sorted x (out of place): {}".format(np.sort(x)))
print()
print("x after sorting is ...")
print()
print(x)
print()

Original x is ...

[ 8  7  7  9 10  9  4 10  2  8]


Sorted x (out of place): [ 2  4  7  7  8  8  9  9 10 10]

x after sorting is ...

[ 8  7  7  9 10  9  4 10  2  8]



Notice that `np.sort()` sorts the array but if the array being sorted has repeated values, they will be retained in the sorted array.

If we don't wish to have repeated values in the sorted result, we can chain the unique function.

In [29]:
print("Sorted, unique x is ... {}".format(np.sort(np.unique(x))))

Sorted, unique x is ... [ 2  4  7  8  9 10]


As we mentioned earlier on, using sort as a method (instead of a function) will modify the array being sorted with the final result.

In [30]:
x = np.random.randint(1, 11, size=(10,))

print("Original x is ...")
print()
print(x)
print()

x.sort()

print("x after sorting is ...")
print()
print(x)
print()

Original x is ...

[ 5  9  9  5  4  1  7  9  5 10]

x after sorting is ...

[ 1  4  5  5  5  7  9  9  9 10]



#### sorting rank 2 arrays

When sorting rank 2 arrays, we need to specify whether we are sorting by rows or by columns. This is done using the `axis` keyword.

In [35]:
x = np.random.randint(1, 11, size=(5, 5))

print("Original x is ...")
print()
print(x)
print()

# sort the columns of x
print()
print("x with sorted columns:")
print("{}".format(np.sort(x, axis=1)))

# sort the rows of x
print()
print("x with sorted rows:")
print("{}".format(np.sort(x, axis=0)))

Original x is ...

[[ 3  8  3  2  5]
 [ 3 10  6  2  3]
 [ 7  5  5  2 10]
 [ 4  3  7  1  4]
 [ 6  9  9  4  3]]


x with sorted columns:
[[ 2  3  3  5  8]
 [ 2  3  3  6 10]
 [ 2  5  5  7 10]
 [ 1  3  4  4  7]
 [ 3  4  6  9  9]]

x with sorted rows:
[[ 3  3  3  1  3]
 [ 3  5  5  2  3]
 [ 4  8  6  2  4]
 [ 6  9  7  2  5]
 [ 7 10  9  4 10]]


## Arithmetic operations and broadcasting

### Broadcasting

This is a term used to describe how NumPy handles element-wise arithmetic operations with ndarrays of different shapes.

Let's start by doing element-wise addition, subtraction, multiplication and division between ndarrays.

To do this, NumPy provides a functional approach such as `np.add()` or by using arithmetic symbols such as `+`. Both forms will do the same operation.

When performing element-wise operations, the ndarrays being operated on must have the same shape or be broadcastable.

Let's start with rank 1 arrays.

In [42]:
x = np.array([1, 2, 3, 4])
y = np.array([5.5, 6.5, 7.5, 8.5])

print("x is ...")
print()
print(x)
print()

print("y is ...")
print()
print(y)
print()

print("x + y = {}".format(x + y))
print("add(x, y) = {}".format(np.add(x, y)))
print()
print("x - y = {}".format(x - y))
print("subtract(x, y) = {}".format(np.subtract(x, y)))
print()
print("x / y = {}".format(x / y))
print("divide(x, y) = {}".format(np.divide(x, y)))
print()
print("x * y = {}".format(x * y))
print("multiply(x, y) = {}".format(np.multiply(x, y)))

x is ...

[1 2 3 4]

y is ...

[5.5 6.5 7.5 8.5]

x + y = [ 6.5  8.5 10.5 12.5]
add(x, y) = [ 6.5  8.5 10.5 12.5]

x - y = [-4.5 -4.5 -4.5 -4.5]
subtract(x, y) = [-4.5 -4.5 -4.5 -4.5]

x / y = [0.18181818 0.30769231 0.4        0.47058824]
divide(x, y) = [0.18181818 0.30769231 0.4        0.47058824]

x * y = [ 5.5 13.  22.5 34. ]
multiply(x, y) = [ 5.5 13.  22.5 34. ]


We can perform the same element-wise operations on rank 2 arrays.

In [45]:
x = np.array([1, 2, 3, 4]).reshape(2, 2)

y = np.array([5.5, 6.5, 7.5, 8.5]).reshape(2, 2)

print("x is ...")
print()
print(x)
print()

print("y is ...")
print()
print(y)
print()

print("x + y = \n {}".format(x + y))
print("add(x, y) = \n {}".format(np.add(x, y)))
print()
print("x - y = \n {}".format(x - y))
print("subtract(x, y) = \n {}".format(np.subtract(x, y)))
print()
print("x / y = \n {}".format(x / y))
print("divide(x, y) = \n {}".format(np.divide(x, y)))
print()
print("x * y = {}".format(x * y))
print("multiply(x, y) = \n {}".format(np.multiply(x, y)))

x is ...

[[1 2]
 [3 4]]

y is ...

[[5.5 6.5]
 [7.5 8.5]]

x + y = 
 [[ 6.5  8.5]
 [10.5 12.5]]
add(x, y) = 
 [[ 6.5  8.5]
 [10.5 12.5]]

x - y = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]
subtract(x, y) = 
 [[-4.5 -4.5]
 [-4.5 -4.5]]

x / y = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]
divide(x, y) = 
 [[0.18181818 0.30769231]
 [0.4        0.47058824]]

x * y = [[ 5.5 13. ]
 [22.5 34. ]]
multiply(x, y) = 
 [[ 5.5 13. ]
 [22.5 34. ]]


Mathematical functions e.g. `sqrt(x)` can be applied to all elements of an ndarray at once.

In [48]:
x = np.array([1, 2, 3, 4])

print("x is ...")
print()
print(x)
print()
print("exp(x) = \n {}".format(np.exp(x)))
print()
print("sqrt(x) = \n {}".format(np.sqrt(x)))
print()
print("power(x, 2) = \n {}".format(np.power(x, 2)))
print()

x is ...

[1 2 3 4]

exp(x) = 
 [ 2.71828183  7.3890561  20.08553692 54.59815003]

sqrt(x) = 
 [1.         1.41421356 1.73205081 2.        ]

power(x, 2) = 
 [ 1  4  9 16]



NumPy has a wide variety of statistical functions. These provide us with statistical information about the elements in an ndarray.

In [58]:
x = np.array([[1, 2], [3, 4]])

print("x is ...")
print()
print(x)
print()

print("The average of all elements in x: {}".format(x.mean()))
print("The average of all elements in THE COLUMNS OF x: {}".format(x.mean(axis=0)))
print("The average of all elements in THE ROWS OF x: {}".format(x.mean(axis=1)))
print()
print("Sum of all elements in x: {}".format(x.sum()))
print("Sum of all elements in THE COLUMNS OF x: {}".format(x.sum(axis=0)))
print("Sum of all elements in THE ROWS OF x: {}".format(x.sum(axis=1)))
print()
print("The standard deviation of all elements in x: {}".format(x.std()))
print("The standard deviation of all elements in THE COLUMNS OF x: {}".format(x.std(axis=0)))
print("The standard deviation of all elements in THE ROWS OF x: {}".format(x.std(axis=1)))
print()
print("The median of all elements in x: {}".format(np.median(x)))
print("The median of all elements in THE COLUMNS OF x: {}".format(np.median(x, axis=0)))
print("The median of all elements in THE ROWS OF x: {}".format(np.median(x, axis=1)))
print()
print("Maximum value of all elements in x: {}".format(x.max()))
print("Maximum value of all elements in THE COLUMNS OF x: {}".format(x.max(axis=0)))
print("Maximum value of all elements in THE ROWS OF x: {}".format(x.max(axis=1)))
print()
print("Minumum value of all elements in x: {}".format(x.min()))
print("Minumum value of all elements in THE COLUMNS OF x: {}".format(x.min(axis=0)))
print("Minumum value of all elements in THE ROWS OF x: {}".format(x.min(axis=1)))

x is ...

[[1 2]
 [3 4]]

The average of all elements in x: 2.5
The average of all elements in THE COLUMNS OF x: [2. 3.]
The average of all elements in THE ROWS OF x: [1.5 3.5]

Sum of all elements in x: 10
Sum of all elements in THE COLUMNS OF x: [4 6]
Sum of all elements in THE ROWS OF x: [3 7]

The standard deviation of all elements in x: 1.118033988749895
The standard deviation of all elements in THE COLUMNS OF x: [1. 1.]
The standard deviation of all elements in THE ROWS OF x: [0.5 0.5]

The median of all elements in x: 2.5
The median of all elements in THE COLUMNS OF x: [2. 3.]
The median of all elements in THE ROWS OF x: [1.5 3.5]

Maximum value of all elements in x: 4
Maximum value of all elements in THE COLUMNS OF x: [3 4]
Maximum value of all elements in THE ROWS OF x: [2 4]

Minumum value of all elements in x: 1
Minumum value of all elements in THE COLUMNS OF x: [1 2]
Minumum value of all elements in THE ROWS OF x: [1 3]


We can also perform operations on single numbers vs all the elements in the ndarray without the use of complicated loops.

In [61]:
x = np.array([[1, 2], [3, 4]])

print("x is ...")
print()
print(x)
print()

print("3 + x = \n {}".format(3 + x))
print()
print("3 * x = \n {}".format(3 * x))
print()
print("x - 3 = \n {}".format(x - 3))
print()
print("x / 3 = \n {}".format(x / 3))
print()

x is ...

[[1 2]
 [3 4]]

3 + x = 
 [[4 5]
 [6 7]]

3 * x = 
 [[ 3  6]
 [ 9 12]]

x - 3 = 
 [[-2 -1]
 [ 0  1]]

x / 3 = 
 [[0.33333333 0.66666667]
 [1.         1.33333333]]



In the example above, NumPy is working behind the scenes to broadcase `3` along the ndarray so that they have the same shape. This allows us e.g. to add 3 to each element of the array with just one line of code.

Subject to constraints, NumPy can also dot the same for ndarrays with different shapes.

In [67]:
x = np.array([1, 2, 3])

y = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

z = np.array([1, 2, 3]).reshape(3, 1)

print("x is ...")
print()
print(x)
print()

print("y is ...")
print()
print(y)
print()

print("z is ...")
print()
print(z)
print()

print("x + y = \n {}".format(x + y))
print()
print("z + y = \n {}".format(z + y))
print()

x is ...

[1 2 3]

y is ...

[[1 2 3]
 [4 5 6]
 [7 8 9]]

z is ...

[[1]
 [2]
 [3]]

x + y = 
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

z + y = 
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]



NumPy was able to add 3 X 1 and 1 X 3 ndarrays to a 3 X 3 ndarray by broadcasting the smaller ndarrays to the big ndarray so that they have compatible shapes. NumPy will do this as long as the smaller array can be expanded to the shape of the larger ndarray in such a way that the resulting broadcast is not ambiguous.